### ISSUE TITLE
PKK5

### ISSUE THREAD

**Issue by davidszakonyi** [GregEremeev/rosreestr-api#1]
Great tool! Quick question - I keep getting timeout errors using the PKK5RosreestrAPIClient. I assume this is a problem with the Rosreestr API. Have you had success using the client with the PKK5 API recently?

**Comment by GregEremeev** [comment]
@davidszakonyi Hey! Sorry for the late reply, I didn't see the notification.

>I assume this is a problem with the Rosreestr API.

Yeah, it depends on the Rorsreestr's app. You can decrease the number of requests to avoid such errors.

>Have you had success using the client with the PKK5 API recently?

Kind of. I was able to use it but after I understood that PKK5 API uses a special type of coordinate system I changed my approach.

You can notice it if you compare it with yandex maps

**Comment by 1000kw** [comment]
Why this requests, formed by PKK5RosreestrAPIClient dont work?
https://pkk5.rosreestr.ru/api/features/1?text=77:17:0000000:11471&limit=11&tolerance=2
https://pkk5.rosreestr.ru/api/features/2?text=55.542%2037.483&limit=11&tolerance=2

**Comment by GregEremeev** [comment]
@1000kw please use a new issue to describe your problem.

I've just checked the server pkk5.rosreestr.ru. It seems that they changed API.

**Comment by pplevar** [comment]
> @1000kw please use a new issue to describe your problem.
> 
> I've just checked the server pkk5.rosreestr.ru. It seems that they changed API.

Will you support new API?

**Comment by GregEremeev** [comment]
@pplevar it depends on the users of this library. If there is a decent amount of people who will need it then I can do it. In another way, you can just create PR on your own.

**Comment by GregEremeev** [comment]
The problem is fixed. You can use 0.3.4 version.
