### ISSUE TITLE
Изменения

### ISSUE THREAD

**Issue by WinterSilence** [GregEremeev/rosreestr-api#2]
https://disk.yandex.ru/i/1xhPCKzcTcQPVw тут еще пара методов и адрес сайта теперь `http://rosreestr.gov.ru`.

**Comment by sergeich5** [comment]
> https://disk.yandex.ru/i/1xhPCKzcTcQPVw тут еще пара методов и адрес сайта теперь `http://rosreestr.gov.ru`.

Ссылка умерла(

**Comment by GregEremeev** [comment]
Closed because of poor description.
